# Configuration for ${project.name}
#
# Version: ${project.version}

plugin-prefix: '&eCustom Messages &8| '
debug-enabled: false

# Configure the format for leave/join messages.
# Remove format to disable.
formats:
  join: '&a+ &7%message%'
  leave: '&c- &7%message%'