# Configuration for ${project.name}
#
# Version: ${project.version}

plugin-prefix: '&eCustom Messages &8| '
debug-enabled: false

# ACTION_BAR, TITLE, TEXT
# Titles support \n for subtitles.
message-position: TEXT

# Extra action bar settings
action-bar:
  duration: 20 # ticks

# Extra title options
# All in ticks
title:
  in: 20
  stay: 40
  out: 20

# Configure the format for leave/join/kill messages.
# Remove format to disable.
formats:
  join: '&8[&a+&8] &7%message%'
  leave: '&8[&c-&8] &7%message%'
  kill: '&8[&4X&8] %message%'