name: ${project.name}
main: ${project.groupId}.MessagePlugin
version: ${project.version}
authors: [ Wertik1206 ]
softdepend: [ PlaceholderAPI ]
commands:
  custommessages:
    aliases: [ cm, messages, custommessage ]
    description: Main plugin command.